apiVersion: v1
kind: Secret
metadata:
  name: uploadstream-db-secret
  namespace: uploadstream
type: Opaque
stringData:
  DB_PASSWORD: uploader
  DB_USER: uploader
  DB_NAME: uploadstream
  DATABASE_URL: "postgres://uploader:uploader@postgres:5432/uploadstream?sslmode=disable"
