apiVersion: v1
kind: Service
metadata:
  name: uploadstream-external
  namespace: uploadstream
  labels:
    app: uploadstream
spec:
  type: LoadBalancer
  ports:
  - port: 50051
    targetPort: grpc
    protocol: TCP
    name: grpc
    nodePort: 30051
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
    nodePort: 30090
  selector:
    app: uploadstream
