
apiVersion: v1
kind: Secret
metadata:
  name: uploadstream-secrets
  namespace: uploadstream
type: Opaque
data:
  # echo -n 'db-password' | base64
  db-password: eW91ci1kYi1wYXNzd29yZA==
  # Database connection string
  # echo -n 'postgres://...' | base64
  database-url: cG9zdGdyZXM6Ly91cGxvYWRlcjp1cGxvYWRlckBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvdXBsb2Fkc3RyZWFtP3NzbG1vZGU9ZGlzYWJsZQ==
